### ISSUE TITLE
Compatibility with audit-argument-checks

### ISSUE THREAD

**Issue by derwaldgeist** [JackAdams/constellation-autopublish#3]
I am using the `audit-argument-checks` package. The `constellation:autopublish` throws the following error in the browser console:

``` js
I20151103-09:02:44.038(1)? Exception from sub Constellation_autopublish id SWP6eoPwNfDPvgy6H Error: Did not check() all arguments during publisher 'Constellation_autopublish'
I20151103-09:02:44.038(1)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20151103-09:02:44.038(1)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20151103-09:02:44.038(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20151103-09:02:44.038(1)?     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
I20151103-09:02:44.038(1)?     at [object Object].subscriptionProto._runHandler (packages/meteorhacks:kadira/lib/hijack/wrap_subscription.js:12:1)
I20151103-09:02:44.038(1)?     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
I20151103-09:02:44.038(1)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
I20151103-09:02:44.038(1)?     at packages/meteorhacks:kadira/lib/hijack/wrap_session.js:77:1
I20151103-09:02:44.038(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151103-09:02:44.039(1)?     at [object Object].sessionProto.protocol_handlers.sub (packages/meteorhacks:kadira/lib/hijack/wrap_session.js:76:1)
```

Seems as if `autopublish` is not checking all arguments.

**Comment by JackAdams** [comment]
Thank you for letting me know this. I wasn't aware of the problem, but it's an easy fix. Will publish a patched release soon.

**Comment by JackAdams** [comment]
I haven't had a chance to test properly, but I've released a new version on atmosphere that should fix this issue.

**Comment by derwaldgeist** [comment]
I tried to add the 0.3.7 version via a package include, but I'm getting the following error:

``` js
error: Conflict: Constraint constellation:autopublish@0.3.7 is not satisfied by constellation:autopublish 0.1.7.
```

Any idea what may cause this? Version 0.3.1 works.

**Comment by JackAdams** [comment]
Thanks for reporting. That's what comes of not testing properly ... I know what's going on and it's my mistake entirely. New release will be out shortly.

**Comment by JackAdams** [comment]
I take that back.  I don't know what's going on.  The mistake I thought I'd made with dependencies wasn't made after all.  If you post your `.packages` and  `.versions files`, I might be able to figure it out.  In the meantime, try `meteor remove babrahams:constellation constellation:autopublish` then `meteor add constellation:autopublish`.

**Comment by derwaldgeist** [comment]
Thanks for your investigation.

Here's the code I was trying to use in my package file:

``` js
Package.onUse(function(api) {
  api.versionsFrom('1.1.0.3');
  // Constellation
  api.use([
    'constellation:console@1.2.3',
    'babrahams:temple@0.3.5',
    'constellation:subscriptions@0.3.3',
    'constellation:session@0.3.4',
    'constellation:autopublish@0.3.7',
    'constellation:tiny@0.3.3',
    'constellation:position@0.3.4'
  ]);
});
```

and here's my .versions file:

```
abpetkov:switchery@0.1.0
accounts-base@1.2.0
accounts-facebook@1.0.4
accounts-google@1.0.4
accounts-oauth@1.1.5
accounts-password@1.1.1
accounts-twitter@1.0.4
aiddogs:fake@0.0.1
aiddogs:home@0.0.1
aiddogs:live-session@0.0.1
aiddogs:messaging@0.0.1
aiddogs:search-experts@0.0.1
aiddogs:sessions@0.0.1
aiddogs:subjects@0.0.1
aiddogs:user-profile@0.0.1
aiddogs:users@0.0.1
alanning:roles@1.2.13
aldeed:autoform@5.5.1
aldeed:collection2@2.5.0
aldeed:http@0.2.2
aldeed:simple-schema@1.3.3
aldeed:template-extension@3.4.3
amplify@1.0.0
anti:fake@0.4.1
arillo:flow-router-helpers@0.4.5
aspin:tokbox@2.3.0
audit-argument-checks@1.0.3
autoupdate@1.2.1
babrahams:editable-json@0.5.7
babrahams:temple@0.3.0
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
cfs:access-point@0.1.49
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:filesystem@0.1.2
cfs:http-methods@0.0.30
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:s3@0.1.3
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.1
cfs:tempstore@0.1.4
cfs:upload-http@0.0.20
cfs:worker@0.1.4
check@1.0.5
chriswessels:hammer@4.0.2
chriswessels:slideout@0.1.9_2
chuangbo:cookie@1.1.0
coffeescript@1.0.6
concats:app-main@0.0.1
concats:debug@0.0.1
concats:media-store@0.0.1
concats:media-store-cfs-s3@0.0.1
concats:media-store-slingshot@0.0.1
concats:test@0.0.1
concats:user-login@0.0.1
concats:user-manager@0.0.1
concats:web-tools@0.0.1
constellation:autopublish@0.3.1
constellation:console@1.2.0
constellation:position@0.3.1
constellation:session@0.3.1
constellation:subscriptions@0.3.0
constellation:tiny@0.3.0
cosmos:browserify@0.5.1
cwaring:modernizr@3.0.0_1
dburles:collection-helpers@1.0.3
dburles:mongo-collection-instances@0.3.4
ddp@1.1.0
deps@1.0.7
edgee:slingshot@0.7.1
ejson@1.0.6
email@1.0.6
facebook@1.2.1
fastclick@1.0.3
flemay:less-autoprefixer@1.1.0
fortawesome:fontawesome@4.4.0
fourq:typeahead@1.0.0
fourseven:scss@3.2.0
francocatena:compass@0.5.1
froatsnook:sleep@1.1.0
geojson-utils@1.0.3
google@1.1.5
grigio:babel@0.1.8
gwendall:autoform-i18n@0.1.9_1
gwendall:body-events@0.1.6
gwendall:session-json@0.1.7
gwendall:simple-schema-i18n@0.1.9
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3
jquery@1.11.3_2
jquery-waypoints@1.0.3
json@1.0.3
kadira:blaze-layout@2.1.0
kadira:debug@2.2.3
kadira:flow-router@2.6.2
lai:collection-extensions@0.1.4
launch-screen@1.0.2
less@1.0.14
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
mcissel:flow-transition@1.0.1
meteor@1.1.6
meteor-platform@1.2.2
meteorhacks:async@1.0.0
meteorhacks:fast-render@2.10.0
meteorhacks:inject-data@1.4.1
meteorhacks:kadira@2.23.4
meteorhacks:meteorx@1.3.1
meteorhacks:npm@1.5.0
meteorhacks:picker@1.0.3
meteorhacks:search-source@1.4.0
meteorhacks:subs-manager@1.6.2
meteorspark:util@0.2.0
meteortoys:toykit@0.8.7
minifiers@1.1.5
minimongo@1.0.8
mizzao:bootboxjs@4.4.0
mobile-status-bar@1.0.3
momentjs:moment@2.10.6
mongo@1.1.0
mongo-livedata@1.0.8
mpowaga:string-template@0.1.0
mquandalle:bower@1.4.1_3
msavin:jetsetter@1.0.20
msavin:mongol@1.1.5
nooitaf:colors@0.0.2
npm-bcrypt@0.7.8_2
npm-container@1.1.0
oauth@1.1.4
oauth1@1.1.4
oauth2@1.1.3
observe-sequence@1.0.6
olragon:uri-js@1.13.1
ordered-dict@1.0.3
package-version-parser@3.0.3
peppelg:bootstrap-3-modal@1.0.3
practicalmeteor:chai@2.1.0_1
practicalmeteor:loglevel@1.2.0_2
raix:eventemitter@0.1.3
raix:handlebar-helpers@0.2.5
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
reywood:publish-composite@1.4.2
risul:accounting@1.0.1
routepolicy@1.0.5
sanjo:jasmine@0.18.0
sanjo:karma@1.7.0
sanjo:long-running-child-process@1.1.3
sanjo:meteor-files-helpers@1.1.0_7
sanjo:meteor-version@1.0.0
semantic:ui@2.1.4
semantic:ui-data@2.1.4
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
simple:reactive-method@1.0.2
softwarerero:accounts-t9n@1.0.9
spacebars@1.0.6
spacebars-compiler@1.0.6
srp@1.0.3
tap:i18n@1.6.1
tap:i18n-ui@0.7.0
templating@1.1.1
tomwasd:flow-router-autoscroll@0.0.2
tracker@1.0.7
twitter@1.1.4
ui@1.0.6
underscore@1.0.3
url@1.0.4
useraccounts:bootstrap@1.12.3
useraccounts:core@1.12.3
useraccounts:flow-routing@1.12.3
velocity:chokidar@1.0.3_1
velocity:core@0.9.3
velocity:html-reporter@0.8.2
velocity:meteor-internals@1.1.0_7
velocity:meteor-stubs@1.1.1
velocity:shim@0.1.0
velocity:source-map-support@0.3.2_1
velocityjs:velocityjs@1.2.1
webapp@1.2.0
webapp-hashing@1.0.3
yogiben:autoform-modals@0.3.6
zimme:active-route@2.3.2
```

BTW: autopublish 0.3.6 does not work either, but 0.3.1 works.

**Comment by JackAdams** [comment]
All right.  Just released a new version of Constellation and this plugin.  I've changed all the Meteor version dependencies back to 1.0.  I'm hoping this will resolve this issue.

**Comment by JackAdams** [comment]
My recommendation is to change the code to:

```
Package.onUse(function(api) {
  api.versionsFrom('1.1.0.3');
  // Constellation
  api.use([
    'constellation:console@1.3.0',
    'babrahams:temple@0.3.6',
    'constellation:subscriptions@0.3.4',
    'constellation:session@0.3.5',
    'constellation:autopublish@0.3.8',
    'constellation:tiny@0.3.4',
    'constellation:position@0.3.5'
  ]);
});
```

This would bring in the necessary bug fixes, plus some handy new features for Constellation.

Alternatively, remove that package entirely and

```
meteor add constellation:console constellation:plugins
```

then use the "Plugins" tab to choose which packages to add.
