### ISSUE TITLE
[object Object] has no method 'find'

### ISSUE THREAD

**Issue by KristerV** [JackAdams/constellation-autopublish#4]
```
I20151104-12:30:19.099(2)? Exception from sub Constellation_autopublish id yvQTgCiBC8eTkh2bj TypeError: Object [object Object] has no method 'find'
I20151104-12:30:19.101(2)?     at packages/constellation_autopublish/autopublish-server.js:5:1
I20151104-12:30:19.101(2)?     at Array.reduce (native)
I20151104-12:30:19.102(2)?     at Function._.reduce._.foldl._.inject (packages/underscore/underscore.js:139:1)
I20151104-12:30:19.102(2)?     at [object Object].Package [as _handler] (packages/constellation_autopublish/autopublish-server.js:2:1)
I20151104-12:30:19.102(2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151104-12:30:19.102(2)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151104-12:30:19.102(2)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151104-12:30:19.102(2)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151104-12:30:19.102(2)?     at livedata_server.js:548:43
```

and autopublish does not actually work. version 0.3.7 with METEOR@1.2.1.

**Comment by JackAdams** [comment]
Thanks for reporting this.  Sounds like you've got a local collection -- that will cause old version of autopublish to choke.  The latest version 0.3.7 might have a fix for it (can't remember if the fix made it into the latest release, but it is fixed on devel).  If 0.3.7 doesn't do it, there will be a bugfix release for this coming out in less than a week.

**Comment by KristerV** [comment]
just updated to 0.3.7 and not fixed. ok, I shall be patient :)

**Comment by JackAdams** [comment]
Just released a new version of Constellation and this plugin.  I'll be interested to hear if this issue is resolved.

**Comment by KristerV** [comment]
so tested 0.3.8 and still got exactly th same error

``` JavaScript
=> Started your app.                          

=> App running at: http://localhost:3000/
I20151114-19:19:41.502(2)? Exception from sub Constellation_autopublish id AHyEctfsRzStCezaP TypeError: Object [object Object] has no method 'find'
I20151114-19:19:41.503(2)?     at Array.reduce (native)
I20151114-19:19:41.503(2)?     at packages/constellation_autopublish/autopublish-server.js:6:1
I20151114-19:19:41.503(2)?     at Function._.reduce._.foldl._.inject (packages/underscore/underscore.js:139:1)
I20151114-19:19:41.503(2)?     at [object Object].Package [as _handler] (packages/constellation_autopublish/autopublish-server.js:3:1)
I20151114-19:19:41.503(2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151114-19:19:41.503(2)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151114-19:19:41.504(2)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151114-19:19:41.504(2)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151114-19:19:41.504(2)?     at livedata_server.js:548:43
I20151114-19:20:01.651(2)? Exception from sub Constellation_autopublish id 98Xsv2pq2wMGWxADf TypeError: Object [object Object] has no method 'find'
I20151114-19:20:01.651(2)?     at packages/constellation_autopublish/autopublish-server.js:6:1
I20151114-19:20:01.652(2)?     at Array.reduce (native)
I20151114-19:20:01.652(2)?     at Function._.reduce._.foldl._.inject (packages/underscore/underscore.js:139:1)
I20151114-19:20:01.652(2)?     at [object Object].Package [as _handler] (packages/constellation_autopublish/autopublish-server.js:3:1)
I20151114-19:20:01.652(2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151114-19:20:01.652(2)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20151114-19:20:01.652(2)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20151114-19:20:01.652(2)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20151114-19:20:01.653(2)?     at livedata_server.js:548:43

bash: meteor list
255kb:meteor-status                 1.4.2  Meteor Status automatically alerts users when the connection to the server has been lost.
accounts-password                   1.1.4  Password support for accounts
alanning:roles                      1.2.14  Authorization package for Meteor
anti:fake                           0.4.1  Random text and data generator
blaze-html-templates                1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
check                               1.1.0  Check whether a value matches a pattern
constellation:autopublish           0.3.8  Autopublish toggle plugin for Constellation
constellation:console               1.3.0  An extensible development console for Meteor
constellation:plugins               0.1.4  A self-service menu of Constellation plugins
constellation:subscriptions         0.3.4  Subscriptions plugin for Constellation
constellation:velocity              0.3.7  Reactive Velocity test reports in Constellation
```
